<?php
require_once dirname(__DIR__).'/includes/functions.php';$id=(int)($_GET['id']??0);$stmt=$con->prepare('SELECT c.*,cc.name category FROM careers c JOIN career_categories cc ON cc.id=c.category_id WHERE c.id=? AND c.is_active=1');$stmt->bind_param('i',$id);$stmt->execute();$career=$stmt->get_result()->fetch_assoc();if(!$career){http_response_code(404);exit('Career not found');}
$stmt=$con->prepare('SELECT s.*,cs.importance FROM career_skills cs JOIN skills s ON s.id=cs.skill_id WHERE cs.career_id=?');$stmt->bind_param('i',$id);$stmt->execute();$skills=$stmt->get_result();
$stmt=$con->prepare('SELECT * FROM career_simulations WHERE career_id=? AND is_active=1');$stmt->bind_param('i',$id);$stmt->execute();$sims=$stmt->get_result();
$viewerId=(int)(user()['id']??0);
$stmt=$con->prepare("SELECT q.*,
    (SELECT COUNT(*) FROM quiz_questions qq WHERE qq.quiz_id=q.id) question_count,
    (SELECT MAX(a.completed_at) FROM quiz_attempts a WHERE a.quiz_id=q.id AND a.user_id=?) last_attempt,
    (SELECT MAX(CASE WHEN a.max_score>0 THEN ROUND(a.score/a.max_score*100) ELSE 0 END) FROM quiz_attempts a WHERE a.quiz_id=q.id AND a.user_id=?) best_score,
    (SELECT MAX(a.passed) FROM quiz_attempts a WHERE a.quiz_id=q.id AND a.user_id=?) has_passed
    FROM quizzes q WHERE q.career_id=? AND q.is_active=1 ORDER BY q.title");
$stmt->bind_param('iiii',$viewerId,$viewerId,$viewerId,$id);$stmt->execute();$quizzes=$stmt->get_result();$pageTitle=$career['title'];require dirname(__DIR__).'/includes/header.php';?>
<div class="container py-5"><a href="<?=url('careers/browse.php')?>" class="text-decoration-none"><i class="bi bi-arrow-left"></i> All careers</a><div class="row g-4 mt-1"><div class="col-lg-8"><div class="card p-4"><span class="badge bg-light text-primary align-self-start"><?=e($career['category'])?></span><h1 class="mt-2"><?=e($career['title'])?></h1><p class="lead"><?=e($career['summary'])?></p><div><?=nl2br(e($career['description']))?></div><hr><h2 class="h5">Skills for this career</h2><div><?php foreach($skills as $s):?><span class="badge bg-primary-subtle text-primary-emphasis me-1 mb-1"><?=e($s['name'])?> · <?=e(str_replace('_',' ',$s['importance']))?></span><?php endforeach?></div></div></div><div class="col-lg-4"><div class="card p-4 mb-4"><h2 class="h5">Career outlook</h2><div class="d-flex justify-content-between"><span>Average salary</span><strong><?=$career['average_salary']?'R'.number_format($career['average_salary']):'Not listed'?></strong></div><div class="d-flex justify-content-between mt-2"><span>Growth</span><strong><?=e(ucwords(str_replace('_',' ',$career['growth_outlook']??'Not listed')))?></strong></div></div></div></div>
<h2 class="mt-5">Simulations</h2><div class="row g-3"><?php foreach($sims as $s):?><div class="col-md-6"><div class="card p-4 h-100"><h3 class="h5"><?=e($s['title'])?></h3><p class="text-muted"><?=e($s['description'])?></p><div class="small mb-3"><?=e(ucfirst($s['difficulty_level']))?> · <?=$s['estimated_duration_minutes']?> min</div><a class="btn btn-primary mt-auto" href="<?=url('simulation/play.php?id='.$s['id'])?>">Start simulation</a></div></div><?php endforeach?></div>
<div class="d-flex justify-content-between align-items-center mt-5"><div><h2 class="mb-1">Career quizzes</h2><p class="text-muted mb-0">Choose a quiz attached to this career. Your results remain visible on this career profile.</p></div><a class="btn btn-primary" href="<?=url('quiz/choose.php?career_id='.$id)?>">View all quizzes</a></div><div class="row g-3 mt-1"><?php foreach($quizzes as $q):?><div class="col-md-6"><div class="card p-4 h-100"><div class="d-flex justify-content-between gap-3"><h3 class="h5"><?=e($q['title'])?></h3><?php if($q['last_attempt']):?><span class="status-pill <?=$q['has_passed']?'status-active':'status-warning'?> align-self-start"><?=$q['has_passed']?'Passed':round((float)$q['best_score']).'% best'?></span><?php endif?></div><p class="text-muted"><?=e($q['description'])?></p><div class="d-flex flex-wrap gap-3 small text-muted mt-auto mb-3"><span><i class="bi bi-question-circle"></i> <?=(int)$q['question_count']?> questions</span><span><i class="bi bi-clock"></i> <?=(int)$q['time_limit_minutes']?> min</span><span><i class="bi bi-check-circle"></i> <?=(int)$q['pass_score']?>% pass</span></div><?php if((int)$q['question_count']>=10):?><a class="btn btn-outline-primary" href="<?=url('quiz/take.php?id='.$q['id'])?>"><?=$q['last_attempt']?'Retake quiz':'Start quiz'?></a><?php else:?><button class="btn btn-light" disabled>Quiz is being prepared</button><?php endif?></div></div><?php endforeach?></div><?php if(!$quizzes->num_rows):?><div class="card p-5 mt-3 text-center text-muted">No active quizzes are attached to this career yet.</div><?php endif?></div>
<button class="career-chat-toggle" type="button" data-bs-toggle="offcanvas" data-bs-target="#careerChat"><i class="bi bi-stars"></i><span>Ask about this career</span></button><div class="offcanvas offcanvas-end career-chat-panel" tabindex="-1" id="careerChat"><div class="offcanvas-header"><div><h2 class="offcanvas-title h5 mb-0">Career Q&amp;A</h2><small class="text-muted"><?=e($career['title'])?></small></div><button class="btn-close" data-bs-dismiss="offcanvas"></button></div><div class="offcanvas-body d-flex flex-column"><div id="careerChatMessages" class="career-chat-messages"><div class="chat-bubble assistant">Ask me about the work, required skills, study paths, or how to prepare for this career.</div></div><form id="careerChatForm" class="mt-auto pt-3"><div class="input-group"><input class="form-control" id="careerChatInput" maxlength="800" placeholder="Ask a career question…" required><button class="btn btn-primary" aria-label="Send"><i class="bi bi-send"></i></button></div></form></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('careerChatForm'),messages=document.getElementById('careerChatMessages'),input=document.getElementById('careerChatInput');form.addEventListener('submit',async e=>{e.preventDefault();const question=input.value.trim();if(!question)return;messages.insertAdjacentHTML('beforeend','<div class="chat-bubble user">'+escapeHtml(question)+'</div>');input.value='';const waiting=document.createElement('div');waiting.className='chat-bubble assistant';waiting.textContent='Thinking…';messages.append(waiting);messages.scrollTop=messages.scrollHeight;const body=new FormData();body.append('csrf',APP.csrf);body.append('career_id','<?=$id?>');body.append('message',question);try{const response=await fetch(APP.base+'ajax/career_chat.php',{method:'POST',body}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'AI is temporarily unavailable.');waiting.textContent=data.reply}catch(error){waiting.textContent=error.message}messages.scrollTop=messages.scrollHeight})});</script><?php require dirname(__DIR__).'/includes/footer.php';?>
