<?php
require_once __DIR__.'/includes/functions.php';require_login();$uid=(int)user()['id'];$stmt=$con->prepare('SELECT name,email,phone,education_level,date_of_birth,profile_image FROM users WHERE id=?');$stmt->bind_param('i',$uid);$stmt->execute();$profile=$stmt->get_result()->fetch_assoc();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals(csrf_token(),$_POST['csrf']??''))$errors[]='Your session token expired.';
 $name=trim($_POST['name']??'');$phone=trim($_POST['phone']??'');$education=$_POST['education_level']??'';$dob=$_POST['date_of_birth']??'';
 if(mb_strlen($name)<2)$errors[]='Enter your full name.';if(!preg_match('/^[0-9+() -]{7,20}$/',$phone))$errors[]='Enter a valid phone number.';if(!in_array($education,['secondary','undergraduate','graduate','other'],true))$errors[]='Choose your education level.';if(!$dob||strtotime($dob)===false||strtotime($dob)>strtotime('-10 years'))$errors[]='Enter a valid date of birth.';
 if(!$errors){$stmt=$con->prepare('UPDATE users SET name=?,phone=?,education_level=?,date_of_birth=?,profile_completed_at=NOW() WHERE id=?');$stmt->bind_param('ssssi',$name,$phone,$education,$dob,$uid);$stmt->execute();$_SESSION['user']['name']=$name;$_SESSION['user']['profile_complete']=true;flash('success','Profile completed. Welcome to CareerSim!');header('Location:'.url(role_home(user()['role'])));exit;}
 $profile=array_merge($profile,compact('name','phone','education'));$profile['date_of_birth']=$dob;
}
$pageTitle='Complete your profile';$bodyClass='profile-onboarding';require __DIR__.'/includes/header.php';?>
<div class="profile-onboarding-shell"><div class="profile-onboarding-card"><div class="profile-step"><span>1</span><div><strong>Complete your profile</strong><small>This is required once before you continue.</small></div></div><h1>Tell us a little about you</h1><p>We use these details to personalize your learning experience. Your contact details are never sent to the AI service.</p><?php foreach($errors as $error):?><div class="alert alert-danger"><?=e($error)?></div><?php endforeach?><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" name="name" value="<?=e($profile['name']??'')?>" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" value="<?=e($profile['email'])?>" disabled><div class="form-text">Your verified account email cannot be changed here.</div></div><div class="col-md-6"><label class="form-label">Phone number</label><input class="form-control" name="phone" value="<?=e($profile['phone']??'')?>" required></div><div class="col-md-6"><label class="form-label">Date of birth</label><input type="date" class="form-control" name="date_of_birth" value="<?=e($profile['date_of_birth']??'')?>" required></div><div class="col-12"><label class="form-label">Education level</label><select class="form-select" name="education_level" required><option value="">Choose level</option><?php foreach(['secondary','undergraduate','graduate','other'] as $level):?><option value="<?=$level?>" <?=($profile['education_level']??'')===$level?'selected':''?>><?=ucfirst($level)?></option><?php endforeach?></select></div><div class="col-12"><button class="btn btn-primary w-100">Save and continue</button></div></form></div></div><?php require __DIR__.'/includes/footer.php';?>
