<?php
require_once dirname(__DIR__).'/includes/functions.php';require_role(['student','counselor']);$uid=(int)user()['id'];$careerId=(int)($_GET['career_id']??0);
$stmt=$con->prepare('SELECT id,title,summary FROM careers WHERE id=? AND is_active=1');$stmt->bind_param('i',$careerId);$stmt->execute();$career=$stmt->get_result()->fetch_assoc();if(!$career){http_response_code(404);exit('Career not found');}
$stmt=$con->prepare("SELECT q.*,COUNT(DISTINCT qq.id) question_count,MAX(a.completed_at) last_attempt,MAX(CASE WHEN a.max_score>0 THEN ROUND(a.score/a.max_score*100) ELSE 0 END) best_score FROM quizzes q LEFT JOIN quiz_questions qq ON qq.quiz_id=q.id LEFT JOIN quiz_attempts a ON a.quiz_id=q.id AND a.user_id=? WHERE q.career_id=? AND q.is_active=1 GROUP BY q.id ORDER BY q.title");$stmt->bind_param('ii',$uid,$careerId);$stmt->execute();$quizzes=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$pageTitle='Choose a quiz';require dirname(__DIR__).'/includes/header.php';?>
<div class="container py-5"><a class="text-decoration-none" href="<?=url('careers/view.php?id='.$careerId)?>"><i class="bi bi-arrow-left"></i> Back to career</a><div class="mt-3 mb-4"><div class="text-muted"><?=e($career['title'])?></div><h1>Choose a quiz</h1><p class="text-muted">Select the knowledge check you want to complete.</p></div>
<div class="row g-4"><?php foreach($quizzes as $quiz):?><div class="col-md-6"><article class="card p-4 h-100"><div class="d-flex justify-content-between gap-3"><div><h2 class="h5"><?=e($quiz['title'])?></h2><p class="text-muted"><?=e($quiz['description'])?></p></div><?php if($quiz['last_attempt']):?><span class="status-pill status-active align-self-start"><?=round($quiz['best_score'])?>% best</span><?php endif?></div><div class="d-flex flex-wrap gap-3 small text-muted mt-auto mb-3"><span><i class="bi bi-question-circle"></i> <?=$quiz['question_count']?> questions</span><span><i class="bi bi-clock"></i> <?=$quiz['time_limit_minutes']?> min</span><span><i class="bi bi-check-circle"></i> <?=$quiz['pass_score']?>% pass</span></div><?php if($quiz['question_count']>=10):?><a class="btn btn-primary" href="<?=url('quiz/take.php?id='.$quiz['id'])?>"><?=$quiz['last_attempt']?'Retake quiz':'Start quiz'?></a><?php else:?><button class="btn btn-light" disabled>Needs 10 questions</button><?php endif?></article></div><?php endforeach?></div>
<?php if(!$quizzes):?><div class="card p-5 text-center text-muted">No active quizzes are available for this career yet.</div><?php endif?></div>
<?php require dirname(__DIR__).'/includes/footer.php';?>
