<?php
require_once dirname(__DIR__).'/includes/functions.php';require_role(['student','counselor']);$uid=(int)user()['id'];
$stmt=$con->prepare("SELECT COUNT(*) completed,(SELECT COUNT(*) FROM career_simulations WHERE is_active=1) available,COALESCE(AVG(CASE WHEN max_possible_score>0 THEN total_score/max_possible_score*100 END),0) avg_score FROM user_simulation_progress WHERE user_id=? AND status='completed'");$stmt->bind_param('i',$uid);$stmt->execute();$sim=$stmt->get_result()->fetch_assoc();
$stmt=$con->prepare("SELECT c.title,AVG(a.score/NULLIF(a.max_score,0)*100) score FROM quiz_attempts a JOIN quizzes q ON q.id=a.quiz_id JOIN careers c ON c.id=q.career_id WHERE a.user_id=? AND a.completed_at IS NOT NULL GROUP BY c.id ORDER BY c.title");$stmt->bind_param('i',$uid);$stmt->execute();$quiz=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt=$con->prepare('SELECT interest_type,score FROM user_interest_scores WHERE user_id=?');$stmt->bind_param('i',$uid);$stmt->execute();$interests=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt=$con->prepare('SELECT r.*,c.title,c.summary FROM career_recommendations r JOIN careers c ON c.id=r.career_id WHERE r.user_id=? ORDER BY r.match_score DESC LIMIT 6');$stmt->bind_param('i',$uid);$stmt->execute();$recs=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt=$con->prepare('SELECT b.*,ub.earned_at FROM user_badges ub JOIN badges b ON b.id=ub.badge_id WHERE ub.user_id=? ORDER BY ub.earned_at DESC');$stmt->bind_param('i',$uid);$stmt->execute();$badges=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$completionPercent=$sim['available']?min(100,round($sim['completed']/$sim['available']*100)):0;$pageTitle='My progress';$bodyClass='progress-page';require dirname(__DIR__).'/includes/header.php';?>
<div class="progress-shell">
 <header class="progress-page-header"><div><h1>My progress</h1><p>Your activity, strengths, and next opportunities.</p></div><form method="post" action="<?=url('ajax/generate_recommendations.php')?>" data-ajax><input type="hidden" name="csrf" value="<?=csrf_token()?>"><button><i class="bi bi-arrow-clockwise"></i> Refresh recommendations</button></form></header>
 <section class="progress-kpi-grid">
  <article class="progress-kpi"><h2>Simulations completed</h2><div><strong><?=$sim['completed']?></strong><span>/ <?=$sim['available']?></span></div><div class="progress-kpi-bar"><span style="width:<?=$completionPercent?>%"></span></div></article>
  <article class="progress-kpi"><h2>Average simulation score</h2><div><strong><?=round($sim['avg_score'])?>%</strong></div><p><?=$sim['completed']?'Across completed simulations':'No data yet'?></p></article>
  <article class="progress-kpi"><h2>Badges earned</h2><div><strong><?=count($badges)?></strong></div><div class="progress-mini-badges"><?php if($badges):foreach(array_slice($badges,0,4) as $b):?><span title="<?=e($b['name'])?>"><i class="bi bi-<?=e($b['icon']?:'award')?>"></i></span><?php endforeach;else:?><span><i class="bi bi-lock"></i></span><?php endif?></div></article>
 </section>
 <div class="progress-bento">
  <section class="progress-panel progress-interest">
   <?php if($interests):?><div class="progress-panel-heading"><h2>Interest profile</h2><i class="bi bi-person-vcard"></i></div><div class="progress-chart"><canvas id="interestChart"></canvas></div>
   <?php else:?><div class="progress-empty-icon"><i class="bi bi-lightbulb"></i></div><h2>Interest profile</h2><p>Complete your interest assessment to unlock a personalized chart showing your career alignment across six RIASEC dimensions.</p><a href="<?=url('assessment/interest.php')?>">Take assessment</a><?php endif?>
  </section>
  <section class="progress-panel progress-quiz"><div class="progress-panel-heading"><h2>Quiz scores</h2><i class="bi bi-patch-question"></i></div><?php if($quiz):?><div class="progress-chart"><canvas id="quizChart"></canvas></div><?php else:?><div class="progress-dashed-empty">Quiz results will appear here as you complete career knowledge checks.</div><?php endif?></section>
  <section class="progress-panel progress-recommendations"><div class="progress-panel-heading"><h2>Career recommendations</h2><a href="<?=url('careers/browse.php')?>">View all <i class="bi bi-arrow-right"></i></a></div>
   <?php if($recs):?><div class="recommendation-grid"><?php foreach($recs as $r):?><a href="<?=url('careers/view.php?id='.$r['career_id'])?>" class="recommendation-tile"><span><i class="bi bi-briefcase"></i></span><div><strong><?=e($r['title'])?></strong><small><?=round($r['match_score'])?>% match · <?=e($r['based_on'])?></small><p><?=e($r['explanation']?:$r['summary'])?></p></div></a><?php endforeach?></div>
   <?php else:?><div class="progress-dashed-empty">Complete the interest assessment or a learning activity to generate smart recommendations tailored to your profile.</div><?php endif?>
  </section>
  <section class="progress-panel progress-badges"><div class="progress-panel-heading"><h2>Badges</h2><i class="bi bi-award"></i></div><div class="badge-gallery"><?php if($badges):foreach($badges as $b):?><div title="<?=e($b['description'])?>"><span><i class="bi bi-<?=e($b['icon']?:'award')?>"></i></span><small><?=e($b['name'])?></small></div><?php endforeach;else:for($i=0;$i<6;$i++):?><div class="locked"><span><i class="bi bi-<?=$i<3?['award','stars','trophy'][$i]:'lock'?>"></i></span></div><?php endfor;endif?></div><?php if(!$badges):?><p class="text-center text-muted small mt-4">Your earned badges will appear here.</p><?php endif?></section>
 </div>
</div>
<script>document.addEventListener('DOMContentLoaded',()=>{<?php if($interests):?>new Chart(document.getElementById('interestChart'),{type:'radar',data:{labels:<?=json_encode(array_map(fn($x)=>ucfirst($x['interest_type']),$interests))?>,datasets:[{label:'RIASEC',data:<?=json_encode(array_column($interests,'score'),JSON_NUMERIC_CHECK)?>,borderColor:'#0d9488',backgroundColor:'rgba(13,148,136,.12)'}]},options:{maintainAspectRatio:false,scales:{r:{min:0,max:100}}}});<?php endif?><?php if($quiz):?>new Chart(document.getElementById('quizChart'),{type:'bar',data:{labels:<?=json_encode(array_column($quiz,'title'))?>,datasets:[{label:'Average %',data:<?=json_encode(array_column($quiz,'score'),JSON_NUMERIC_CHECK)?>,backgroundColor:'#131b2e'}]},options:{maintainAspectRatio:false,scales:{y:{beginAtZero:true,max:100}}}});<?php endif?>});</script>
<?php require dirname(__DIR__).'/includes/footer.php';?>
