<?php
require_once dirname(__DIR__).'/includes/functions.php';require_role('student');$uid=(int)user()['id'];$q=trim($_GET['q']??'');$type=$_GET['type']??'';$like='%'.$q.'%';
$sql="SELECT j.*,c.title career_title,a.id application_id,a.status application_status FROM job_opportunities j LEFT JOIN careers c ON c.id=j.career_id LEFT JOIN job_applications a ON a.job_id=j.id AND a.user_id=? WHERE j.is_active=1 AND (j.closing_date IS NULL OR j.closing_date>=CURDATE()) AND (j.title LIKE ? OR j.company LIKE ? OR j.location LIKE ?)";
$params=[$uid,$like,$like,$like];$types='isss';if(in_array($type,['internship','learnership','part_time','full_time','contract'],true)){$sql.=' AND j.employment_type=?';$params[]=$type;$types.='s';}$sql.=' ORDER BY j.created_at DESC';
$stmt=$con->prepare($sql);$stmt->bind_param($types,...$params);$stmt->execute();$jobs=$stmt->get_result();$profile=$con->query("SELECT resume_path FROM users WHERE id=$uid")->fetch_assoc();
$pageTitle='Job opportunities';require dirname(__DIR__).'/includes/header.php';?>
<div class="container py-5 job-page"><div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><h1>Job opportunities</h1><p class="text-muted mb-0">Apply to roles that match the career skills you are building.</p></div><a class="btn btn-outline-primary align-self-start" href="<?=url('jobs/applications.php')?>"><i class="bi bi-clipboard-check"></i> My applications</a></div>
<form class="card p-3 mb-4"><div class="row g-2"><div class="col-md"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Search title, company, or location"></div><div class="col-md-3"><select class="form-select" name="type"><option value="">All opportunity types</option><?php foreach(['internship','learnership','part_time','full_time','contract'] as $x):?><option value="<?=$x?>" <?=$type===$x?'selected':''?>><?=e(ucwords(str_replace('_',' ',$x)))?></option><?php endforeach?></select></div><div class="col-md-auto"><button class="btn btn-primary w-100">Search</button></div></div></form>
<?php if(!$profile['resume_path']):?><div class="alert alert-info"><i class="bi bi-info-circle"></i> Upload your resume in your <a href="<?=url('dashboard/profile.php')?>">career profile</a> before applying.</div><?php endif?>
<div class="row g-4"><?php foreach($jobs as $job):?><div class="col-lg-6"><article class="card job-card h-100 p-4"><div class="d-flex justify-content-between gap-3"><div><span class="job-type"><?=e(ucwords(str_replace('_',' ',$job['employment_type'])))?></span><h2 class="h4 mt-3 mb-1"><?=e($job['title'])?></h2><strong><?=e($job['company'])?></strong></div><i class="bi bi-building job-building"></i></div><div class="text-muted my-3"><i class="bi bi-geo-alt"></i> <?=e($job['location']?:'Location flexible')?><?php if($job['career_title']):?> · <?=e($job['career_title'])?><?php endif?></div><p><?=e($job['description'])?></p><?php if($job['requirements']):?><details class="mb-3"><summary class="fw-semibold">Requirements</summary><div class="small text-muted mt-2"><?=nl2br(e($job['requirements']))?></div></details><?php endif?><div class="mt-auto d-flex justify-content-between align-items-center"><small class="text-muted"><?=$job['closing_date']?'Closes '.e($job['closing_date']):'Open until filled'?></small><?php if($job['application_id']):?><span class="status-pill status-active"><?=e(ucwords(str_replace('_',' ',$job['application_status'])))?></span><?php else:?><button class="btn btn-primary btn-sm apply-job" data-id="<?=$job['id']?>" data-title="<?=e($job['title'])?>" <?=$profile['resume_path']?'':'disabled'?>>Apply now</button><?php endif?></div></article></div><?php endforeach?></div><?php if(!$jobs->num_rows):?><div class="card p-5 text-center text-muted">No open opportunities match your search.</div><?php endif?></div>
<div class="modal fade" id="applyModal"><div class="modal-dialog"><form class="modal-content" action="<?=url('jobs/apply.php')?>" method="post" data-ajax><div class="modal-header"><div><h2 class="modal-title fs-5">Apply for this opportunity</h2><div class="small text-muted" id="applyTitle"></div></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="job_id"><div class="alert alert-light border"><i class="bi bi-file-earmark-person"></i> Your saved resume will be attached.</div><label class="form-label">Cover letter <span class="text-muted">(optional)</span></label><textarea class="form-control" name="cover_letter" rows="7" maxlength="3000" placeholder="Explain why you are interested and what you can contribute."></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Submit application</button></div></form></div></div>
<script>document.querySelectorAll('.apply-job').forEach(b=>b.onclick=()=>{const m=document.getElementById('applyModal');m.querySelector('[name=job_id]').value=b.dataset.id;document.getElementById('applyTitle').textContent=b.dataset.title;bootstrap.Modal.getOrCreateInstance(m).show()});</script>
<?php require dirname(__DIR__).'/includes/footer.php';?>
