<?php
require_once dirname(__DIR__).'/includes/functions.php';require_content_manager();
$jobId=(int)($_GET['job_id']??0);$status=$_GET['status']??'';$statuses=['submitted','under_review','shortlisted','unsuccessful','accepted'];$where=[];$types='';$params=[];
if($jobId){$where[]='a.job_id=?';$types.='i';$params[]=$jobId;}if(in_array($status,$statuses,true)){$where[]='a.status=?';$types.='s';$params[]=$status;}
$sql="SELECT a.id,a.status,a.applied_at,u.name,j.title job_title,j.company,c.title career_title,(SELECT COUNT(*) FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE qa.user_id=a.user_id AND (j.career_id IS NULL OR q.career_id=j.career_id)) quiz_attempts FROM job_applications a JOIN users u ON u.id=a.user_id JOIN job_opportunities j ON j.id=a.job_id LEFT JOIN careers c ON c.id=j.career_id".($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY a.applied_at DESC';
$stmt=$con->prepare($sql);if($params)$stmt->bind_param($types,...$params);$stmt->execute();$applications=$stmt->get_result();$jobs=$con->query('SELECT id,title,company FROM job_opportunities ORDER BY created_at DESC');$pageTitle='Job applications';require __DIR__.'/includes/header.php';?>
<section class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4"><div><div class="admin-page-kicker">Applicant review</div><h1 class="h3">Job applications</h1><p class="text-muted mb-0">Review profiles, education, resumes, and relevant quiz performance.</p></div><form class="d-flex gap-2"><select class="form-select" name="job_id"><option value="">All jobs</option><?php foreach($jobs as $job):?><option value="<?=$job['id']?>" <?=$jobId===(int)$job['id']?'selected':''?>><?=e($job['title'].' · '.$job['company'])?></option><?php endforeach?></select><select class="form-select" name="status"><option value="">All statuses</option><?php foreach($statuses as $value):?><option value="<?=$value?>" <?=$status===$value?'selected':''?>><?=e(ucwords(str_replace('_',' ',$value)))?></option><?php endforeach?></select><button class="btn btn-outline-primary">Filter</button></form></section>
<div class="card overflow-hidden"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Applicant</th><th>Opportunity</th><th>Relevant quizzes</th><th>Applied</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($applications as $a):?><tr><td><strong><?=e($a['name'])?></strong></td><td><strong><?=e($a['job_title'])?></strong><div class="small text-muted"><?=e($a['company'])?><?=$a['career_title']?' · '.e($a['career_title']):''?></div></td><td><?=(int)$a['quiz_attempts']?> attempts</td><td><?=e($a['applied_at'])?></td><td><?=e(ucwords(str_replace('_',' ',$a['status'])))?></td><td class="text-end"><button class="btn btn-sm btn-outline-primary review-application" data-id="<?=$a['id']?>">Review</button></td></tr><?php endforeach?></tbody></table></div></div><?php if(!$applications->num_rows):?><div class="card p-5 text-center text-muted mt-3">No applications match these filters.</div><?php endif?>
<div class="modal fade" id="applicationModal"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Review application</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="applicationModalBody"></div></div></div></div>
<script>
document.addEventListener('click',async e=>{const b=e.target.closest('.review-application');if(!b)return;const m=bootstrap.Modal.getOrCreateInstance(applicationModal);applicationModalBody.innerHTML='<div class="text-center py-5"><span class="spinner-border"></span></div>';m.show();try{const r=await fetch(APP.base+'admin/application_view.php?id='+b.dataset.id);if(!r.ok)throw Error('Application could not be loaded.');applicationModalBody.innerHTML=await r.text()}catch(x){applicationModalBody.innerHTML='<div class="alert alert-danger">'+escapeHtml(x.message)+'</div>'}});
document.addEventListener('click',async e=>{const b=e.target.closest('.analyse-application');if(!b)return;b.disabled=true;try{const f=new FormData();f.set('csrf',APP.csrf);f.set('application_id',b.dataset.id);const r=await fetch(APP.base+'admin/ai_application_analysis.php',{method:'POST',body:f}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.message||'AI is temporarily unavailable.');applicationAiResult.innerHTML='<strong>Summary</strong><p>'+escapeHtml(d.analysis.summary)+'</p><strong>Strengths</strong><ul>'+d.analysis.strengths.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ul><strong>Gaps to verify</strong><ul>'+d.analysis.gaps.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ul><strong>Interview questions</strong><ul>'+d.analysis.interview_questions.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ul>';applicationAiResult.classList.remove('d-none')}catch(x){toast(x.message,'danger')}finally{b.disabled=false}});
document.addEventListener('submit',async e=>{const f=e.target.closest('.application-review-form');if(!f)return;e.preventDefault();try{const r=await fetch(f.action,{method:'POST',body:new FormData(f)}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.message);toast(d.message,'success');setTimeout(()=>location.reload(),400)}catch(x){toast(x.message,'danger')}});
</script><?php require __DIR__.'/includes/footer.php';?>
