<?php
require_once dirname(__DIR__).'/includes/functions.php';require_content_manager();
$entity=$_GET['entity']??$_POST['entity']??'';$id=(int)($_GET['id']??$_POST['id']??0);$allowed=['career','simulation','quiz','interest_question','badge'];if(!in_array($entity,$allowed,true)){http_response_code(404);exit('Unknown content type');}
$tables=['career'=>'careers','simulation'=>'career_simulations','quiz'=>'quizzes','interest_question'=>'interest_questions','badge'=>'badges'];$row=[];if($id){$stmt=$con->prepare("SELECT * FROM {$tables[$entity]} WHERE id=?");$stmt->bind_param('i',$id);$stmt->execute();$row=$stmt->get_result()->fetch_assoc()?:[];}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals(csrf_token(),$_POST['csrf']??'')){flash('danger','Session token expired.');}
 else try{
  if($entity==='career'){$category=(int)$_POST['category_id'];$title=trim($_POST['title']);$slug=trim($_POST['slug']);$summary=trim($_POST['summary']);$description=trim($_POST['description']);$salary=(float)$_POST['average_salary'];$growth=$_POST['growth_outlook'];$active=isset($_POST['is_active'])?1:0;if($id){$s=$con->prepare('UPDATE careers SET category_id=?,title=?,slug=?,summary=?,description=?,average_salary=?,growth_outlook=?,is_active=? WHERE id=?');$s->bind_param('issssdssi',$category,$title,$slug,$summary,$description,$salary,$growth,$active,$id);}else{$s=$con->prepare('INSERT INTO careers(category_id,title,slug,summary,description,average_salary,growth_outlook,is_active) VALUES(?,?,?,?,?,?,?,?)');$s->bind_param('issssdsi',$category,$title,$slug,$summary,$description,$salary,$growth,$active);}}
  elseif($entity==='simulation'){$career=(int)$_POST['career_id'];$title=trim($_POST['title']);$description=trim($_POST['description']);$difficulty=$_POST['difficulty_level'];$duration=(int)$_POST['estimated_duration_minutes'];$active=isset($_POST['is_active'])?1:0;if($id){$s=$con->prepare('UPDATE career_simulations SET career_id=?,title=?,description=?,difficulty_level=?,estimated_duration_minutes=?,is_active=? WHERE id=?');$s->bind_param('isssiii',$career,$title,$description,$difficulty,$duration,$active,$id);}else{$s=$con->prepare('INSERT INTO career_simulations(career_id,title,description,difficulty_level,estimated_duration_minutes,is_active) VALUES(?,?,?,?,?,?)');$s->bind_param('isssii',$career,$title,$description,$difficulty,$duration,$active);}}
  elseif($entity==='quiz'){$career=(int)$_POST['career_id'];$title=trim($_POST['title']);$description=trim($_POST['description']);$pass=(int)$_POST['pass_score'];$time=(int)$_POST['time_limit_minutes'];$active=isset($_POST['is_active'])?1:0;if($id){$s=$con->prepare('UPDATE quizzes SET career_id=?,title=?,description=?,pass_score=?,time_limit_minutes=?,is_active=? WHERE id=?');$s->bind_param('issiiii',$career,$title,$description,$pass,$time,$active,$id);}else{$s=$con->prepare('INSERT INTO quizzes(career_id,title,description,pass_score,time_limit_minutes,is_active) VALUES(?,?,?,?,?,?)');$s->bind_param('issiii',$career,$title,$description,$pass,$time,$active);}}
  elseif($entity==='interest_question'){$text=trim($_POST['question_text']);$type=$_POST['interest_type'];$active=isset($_POST['is_active'])?1:0;if($id){$s=$con->prepare('UPDATE interest_questions SET question_text=?,interest_type=?,is_active=? WHERE id=?');$s->bind_param('ssii',$text,$type,$active,$id);}else{$s=$con->prepare('INSERT INTO interest_questions(question_text,interest_type,is_active) VALUES(?,?,?)');$s->bind_param('ssi',$text,$type,$active);}}
  else{$name=trim($_POST['name']);$description=trim($_POST['description']);$icon=trim($_POST['icon']);$type=$_POST['criteria_type'];$value=(int)$_POST['criteria_value'];if($id){$s=$con->prepare('UPDATE badges SET name=?,description=?,icon=?,criteria_type=?,criteria_value=? WHERE id=?');$s->bind_param('ssssii',$name,$description,$icon,$type,$value,$id);}else{$s=$con->prepare('INSERT INTO badges(name,description,icon,criteria_type,criteria_value) VALUES(?,?,?,?,?)');$s->bind_param('ssssi',$name,$description,$icon,$type,$value);}}
  $s->execute();$savedId=$id?:$con->insert_id;admin_log($con,$id?'update':'create',$entity,$savedId,'Content saved by content manager');
  if(($_SERVER['HTTP_X_REQUESTED_WITH']??'')==='XMLHttpRequest')json_response(['ok'=>true,'message'=>'Content saved successfully.','reload'=>true]);
  flash('success','Content saved successfully.');$dest=['career'=>'careers.php','simulation'=>'simulations.php','quiz'=>'quizzes.php','interest_question'=>'interest_questions.php','badge'=>'badges.php'][$entity];header('Location:'.url('admin/'.$dest));exit;
 }catch(Throwable $e){if(($_SERVER['HTTP_X_REQUESTED_WITH']??'')==='XMLHttpRequest')json_response(['ok'=>false,'message'=>$e->getMessage()],422);flash('danger',$e->getMessage());}
}
$careers=$con->query('SELECT id,title FROM careers ORDER BY title');$categories=$con->query('SELECT id,name FROM career_categories ORDER BY name');$pageTitle=($id?'Edit ':'Add ').str_replace('_',' ',$entity);require __DIR__.'/includes/header.php';?>
<div class="card p-4 mx-auto content-editor-card" style="max-width:850px"><h1 class="h3"><?=e(ucwords($pageTitle))?></h1><form method="post" action="<?=url('admin/content_edit.php?entity='.urlencode($entity).($id?'&id='.$id:''))?>" class="row g-3 content-editor-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="entity" value="<?=e($entity)?>"><input type="hidden" name="id" value="<?=$id?>">
<?php if($entity==='career'):?><div class="col-md-6"><label class="form-label">Category</label><select class="form-select" name="category_id" required><?php foreach($categories as $x):?><option value="<?=$x['id']?>" <?=($row['category_id']??0)==$x['id']?'selected':''?>><?=e($x['name'])?></option><?php endforeach?></select></div><div class="col-md-6"><label class="form-label">Title</label><input class="form-control" name="title" value="<?=e($row['title']??'')?>" required></div><div class="col-md-6"><label class="form-label">Slug</label><input class="form-control" name="slug" value="<?=e($row['slug']??'')?>" required></div><div class="col-md-6"><label class="form-label">Average salary</label><input type="number" class="form-control" name="average_salary" value="<?=e($row['average_salary']??0)?>"></div><div class="col-12"><label class="form-label">Summary</label><textarea class="form-control" name="summary"><?=e($row['summary']??'')?></textarea></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" rows="5" name="description"><?=e($row['description']??'')?></textarea></div><div class="col-md-6"><label class="form-label">Growth outlook</label><select class="form-select" name="growth_outlook"><?php foreach(['declining','stable','growing','high_growth'] as $x):?><option <?=$x===($row['growth_outlook']??'')?'selected':''?>><?=$x?></option><?php endforeach?></select></div>
<?php elseif(in_array($entity,['simulation','quiz'])):?><div class="col-md-6"><label class="form-label">Career</label><select class="form-select" name="career_id"><?php foreach($careers as $x):?><option value="<?=$x['id']?>" <?=($row['career_id']??0)==$x['id']?'selected':''?>><?=e($x['title'])?></option><?php endforeach?></select></div><div class="col-md-6"><label class="form-label">Title</label><input class="form-control" name="title" value="<?=e($row['title']??'')?>" required></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description"><?=e($row['description']??'')?></textarea></div><?php if($entity==='simulation'):?><div class="col-md-6"><label class="form-label">Difficulty</label><select class="form-select" name="difficulty_level"><?php foreach(['beginner','intermediate','advanced'] as $x):?><option <?=$x===($row['difficulty_level']??'')?'selected':''?>><?=$x?></option><?php endforeach?></select></div><div class="col-md-6"><label class="form-label">Duration minutes</label><input type="number" class="form-control" name="estimated_duration_minutes" value="<?=e($row['estimated_duration_minutes']??30)?>"></div><?php else:?><div class="col-md-6"><label class="form-label">Pass score %</label><input type="number" class="form-control" name="pass_score" value="<?=e($row['pass_score']??60)?>"></div><div class="col-md-6"><label class="form-label">Time limit minutes</label><input type="number" class="form-control" name="time_limit_minutes" value="<?=e($row['time_limit_minutes']??15)?>"></div><?php endif?>
<?php elseif($entity==='interest_question'):?><div class="col-12"><label class="form-label">Question</label><textarea class="form-control" name="question_text" required><?=e($row['question_text']??'')?></textarea></div><div class="col-md-6"><label class="form-label">RIASEC type</label><select class="form-select" name="interest_type"><?php foreach(['realistic','investigative','artistic','social','enterprising','conventional'] as $x):?><option <?=$x===($row['interest_type']??'')?'selected':''?>><?=$x?></option><?php endforeach?></select></div>
<?php else:?><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" value="<?=e($row['name']??'')?>" required></div><div class="col-md-6"><label class="form-label">Icon</label><input class="form-control" name="icon" value="<?=e($row['icon']??'award')?>"></div><div class="col-12"><label class="form-label">Description</label><input class="form-control" name="description" value="<?=e($row['description']??'')?>"></div><div class="col-md-6"><label class="form-label">Criteria</label><select class="form-select" name="criteria_type"><?php foreach(['simulation_complete','quiz_pass','career_count','streak'] as $x):?><option <?=$x===($row['criteria_type']??'')?'selected':''?>><?=$x?></option><?php endforeach?></select></div><div class="col-md-6"><label class="form-label">Required value</label><input type="number" class="form-control" name="criteria_value" value="<?=e($row['criteria_value']??1)?>"></div><?php endif?>
<?php if($entity!=='badge'):?><div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" <?=($row['is_active']??1)?'checked':''?>> Active</label></div><?php endif?><div class="col-12"><button class="btn btn-primary">Save</button> <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button></div></form></div><?php require __DIR__.'/includes/footer.php';?>
