<?php
require_once dirname(__DIR__).'/includes/functions.php';require_admin();
if(($_GET['export']??'')==='csv'){header('Content-Type:text/csv');header('Content-Disposition:attachment; filename=feedback.csv');$o=fopen('php://output','w');fputcsv($o,['Student','Simulation','Rating','Comment','Status','Admin response','Created']);foreach($con->query('SELECT u.name,s.title,f.rating,f.comment,f.moderation_status,f.admin_response,f.created_at FROM simulation_feedback f JOIN users u ON u.id=f.user_id JOIN career_simulations s ON s.id=f.simulation_id ORDER BY f.created_at DESC') as $r)fputcsv($o,$r);exit;}
$rating=(int)($_GET['rating']??0);$status=$_GET['status']??'';$where=[];if($rating)$where[]='f.rating='.$rating;if(in_array($status,['new','flagged','dismissed','responded'],true))$where[]="f.moderation_status='".$con->real_escape_string($status)."'";$sql='SELECT u.name,u.email,s.title,f.* FROM simulation_feedback f JOIN users u ON u.id=f.user_id JOIN career_simulations s ON s.id=f.simulation_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY f.created_at DESC';$rows=$con->query($sql);$pageTitle='Feedback';require __DIR__.'/includes/header.php';?>
<div class="d-flex justify-content-between align-items-start"><div><h1 class="h3">Simulation feedback</h1><p class="text-muted">Review, flag, dismiss, or respond to student feedback.</p></div><a class="btn btn-outline-primary" href="?export=csv">Export CSV</a></div>
<form class="row g-2 mb-3"><div class="col-md-4"><select class="form-select" name="rating"><option value="0">All ratings</option><?php for($i=5;$i>=1;$i--):?><option value="<?=$i?>" <?=$rating===$i?'selected':''?>><?=$i?> stars</option><?php endfor?></select></div><div class="col-md-4"><select class="form-select" name="status"><option value="">All statuses</option><?php foreach(['new','flagged','dismissed','responded'] as $x):?><option value="<?=$x?>" <?=$status===$x?'selected':''?>><?=ucfirst($x)?></option><?php endforeach?></select></div><div class="col-md-2"><button class="btn btn-primary">Filter</button></div></form>
<div class="card table-responsive"><table class="table mb-0"><thead><tr><th>Student</th><th>Simulation</th><th>Rating</th><th>Comment</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['name'])?></td><td><?=e($r['title'])?></td><td><?=str_repeat('★',(int)$r['rating'])?></td><td><?=e($r['comment'])?></td><td><span class="status-pill status-<?=$r['moderation_status']==='new'?'inactive':'active'?>"><?=e($r['moderation_status'])?></span></td><td><button class="btn btn-sm btn-outline-primary moderate" data-row='<?=e(json_encode($r))?>'>Moderate</button></td></tr><?php endforeach?></tbody></table></div>
<div class="modal fade" id="moderateModal"><div class="modal-dialog"><form class="modal-content" action="<?=url('admin/moderate_feedback.php')?>" method="post" data-ajax><div class="modal-header"><h2 class="modal-title fs-5">Moderate feedback</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="feedback_id"><label class="form-label">Status</label><select class="form-select mb-3" name="moderation_status"><?php foreach(['new','flagged','dismissed','responded'] as $x):?><option value="<?=$x?>"><?=ucfirst($x)?></option><?php endforeach?></select><label class="form-label">Administrator response</label><textarea class="form-control" name="admin_response" maxlength="500" rows="4"></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save moderation</button></div></form></div></div>
<script>document.querySelectorAll('.moderate').forEach(button=>button.addEventListener('click',()=>{const row=JSON.parse(button.dataset.row),form=document.querySelector('#moderateModal form');form.elements.feedback_id.value=row.id;form.elements.moderation_status.value=row.moderation_status;form.elements.admin_response.value=row.admin_response??'';bootstrap.Modal.getOrCreateInstance(document.getElementById('moderateModal')).show()}));</script><?php require __DIR__.'/includes/footer.php';?>
