<?php
require_once dirname(__DIR__).'/includes/functions.php';require_content_manager();verify_csrf();
$simulationId=(int)($_POST['simulation_id']??0);$title=trim($_POST['title']??'');$instructions=trim($_POST['instructions']??'');$type=$_POST['task_type']??'';$max=max(0,min(1000,(int)($_POST['max_score']??10)));
if(!$simulationId||$title===''||$instructions===''||!in_array($type,['scenario_choice','case_study','practical_exercise','reflection'],true))json_response(['ok'=>false,'message'=>'Complete all required task fields.'],422);
$options=array_map('trim',(array)($_POST['options']??[]));$scores=(array)($_POST['option_scores']??[]);$feedback=(array)($_POST['option_feedback']??[]);$best=(int)($_POST['best_option']??-1);
if(in_array($type,['scenario_choice','case_study'],true)&&(count(array_filter($options))<2||$best<0))json_response(['ok'=>false,'message'=>'Choice tasks require at least two options and a best option.'],422);
$order=(int)$con->query("SELECT COALESCE(MAX(sort_order),0)+1 n FROM simulation_tasks WHERE simulation_id=$simulationId")->fetch_assoc()['n'];$con->begin_transaction();try{$stmt=$con->prepare('INSERT INTO simulation_tasks(simulation_id,title,instructions,task_type,sort_order,max_score) VALUES(?,?,?,?,?,?)');$stmt->bind_param('isssii',$simulationId,$title,$instructions,$type,$order,$max);$stmt->execute();$taskId=$con->insert_id;
if(in_array($type,['scenario_choice','case_study'],true)){$insert=$con->prepare('INSERT INTO task_options(task_id,option_text,score_value,feedback_text,is_best_practice,sort_order) VALUES(?,?,?,?,?,?)');foreach($options as $i=>$text){if($text==='')continue;$score=(int)($scores[$i]??0);$note=trim($feedback[$i]??'');$isBest=$i===$best?1:0;$sort=$i+1;$insert->bind_param('isisii',$taskId,$text,$score,$note,$isBest,$sort);$insert->execute();}}
$con->commit();admin_log($con,'create','simulation_task',$taskId,'Created task with manager builder');json_response(['ok'=>true,'message'=>'Simulation task added.','reload'=>true]);}catch(Throwable $e){$con->rollback();json_response(['ok'=>false,'message'=>'The task could not be saved.'],500);}
