<?php
require_once dirname(__DIR__).'/includes/functions.php';require_role(['admin','content_manager']);verify_csrf();$entity=$_POST['entity']??'';$id=(int)($_POST['id']??0);
try{
if(in_array($entity,['category','skill'],true) && user()['role']!=='content_manager')throw new RuntimeException('Only content managers can change learning content.');
if($entity==='user' && user()['role']!=='admin')throw new RuntimeException('Only administrators can manage users.');
if($entity==='category'){$name=trim($_POST['name']??'');$slug=trim($_POST['slug']??'');$icon=trim($_POST['icon']??'');if(!$name||!$slug)throw new RuntimeException('Name and slug are required.');if($id){$s=$con->prepare('UPDATE career_categories SET name=?,slug=?,icon=? WHERE id=?');$s->bind_param('sssi',$name,$slug,$icon,$id);}else{$s=$con->prepare('INSERT INTO career_categories(name,slug,icon) VALUES(?,?,?)');$s->bind_param('sss',$name,$slug,$icon);}$s->execute();$id=$id?:$con->insert_id;}
elseif($entity==='skill'){$name=trim($_POST['name']??'');if(!$name)throw new RuntimeException('Name is required.');if($id){$s=$con->prepare('UPDATE skills SET name=? WHERE id=?');$s->bind_param('si',$name,$id);}else{$s=$con->prepare('INSERT INTO skills(name) VALUES(?)');$s->bind_param('s',$name);}$s->execute();$id=$id?:$con->insert_id;}
elseif($entity==='user'){$role=$_POST['role']??'';$status=$_POST['status']??'';if(!in_array($role,['student','counselor','content_manager','admin'])||!in_array($status,['pending','active','suspended']))throw new RuntimeException('Invalid role or status.');if($id===(int)user()['id']&&($role!=='admin'||$status!=='active'))throw new RuntimeException('You cannot remove your own admin access.');$s=$con->prepare('UPDATE users SET role=?,status=? WHERE id=?');$s->bind_param('ssi',$role,$status,$id);$s->execute();}
else throw new RuntimeException('Unsupported action.');admin_log($con,$id?'update':'create',$entity,$id,'Saved via admin modal');json_response(['ok'=>true,'message'=>'Saved successfully.','reload'=>true]);}catch(Throwable $e){json_response(['ok'=>false,'message'=>$e->getMessage()],422);}
