<?php
require_once dirname(__DIR__).'/includes/functions.php';require_content_manager();
$rows=$con->query('SELECT s.*,c.title career,(SELECT COUNT(*) FROM simulation_tasks t WHERE t.simulation_id=s.id) tasks FROM career_simulations s JOIN careers c ON c.id=s.career_id ORDER BY s.created_at DESC')->fetch_all(MYSQLI_ASSOC);
$aiOptions=array_map(fn($r)=>['id'=>$r['id'],'label'=>$r['career'].' — '.$r['title']],$rows);
$pageTitle='Simulations';require __DIR__.'/includes/header.php';?>
<div class="d-flex justify-content-between align-items-start gap-3"><div><h1 class="h3">Simulations</h1><p class="text-muted">Manage workplace simulation modules.</p></div><div class="d-flex align-items-start gap-2"><button class="btn btn-outline-primary ai-generate" data-kind="simulation_tasks" data-options="<?=e(json_encode($aiOptions))?>"><i class="bi bi-stars"></i> Generate tasks</button><a class="btn btn-primary create-action content-editor-link" href="<?=url('admin/content_edit.php?entity=simulation')?>"><i class="bi bi-plus-circle"></i><span>Add simulation</span></a></div></div>
<div class="card table-responsive"><table class="table mb-0"><thead><tr><th>Simulation</th><th>Career</th><th>Difficulty</th><th>Tasks</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['title'])?></td><td><?=e($r['career'])?></td><td><?=e($r['difficulty_level'])?></td><td><?=$r['tasks']?></td><td class="text-end"><button class="btn btn-sm btn-outline-primary add-simulation-task" data-id="<?=$r['id']?>" data-title="<?=e($r['title'])?>"><i class="bi bi-plus-circle"></i> Add task</button> <a class="btn btn-sm btn-outline-primary content-editor-link" href="<?=url('admin/content_edit.php?entity=simulation&id='.$r['id'])?>">Edit</a></td></tr><?php endforeach?></tbody></table></div>
<div class="modal fade" id="taskModal"><div class="modal-dialog modal-lg modal-dialog-scrollable"><form class="modal-content" id="taskForm"><div class="modal-header"><div><h2 class="modal-title fs-5">Add simulation task</h2><small class="text-muted" id="taskTarget"></small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="simulation_id"><div class="row g-3"><div class="col-md-8"><label class="form-label">Task title</label><input class="form-control" name="title" required></div><div class="col-md-4"><label class="form-label">Task type</label><select class="form-select" name="task_type" id="taskType"><option value="scenario_choice">Scenario choice</option><option value="case_study">Case study</option><option value="practical_exercise">Practical exercise</option><option value="reflection">Reflection</option></select></div><div class="col-12"><label class="form-label">Instructions</label><textarea class="form-control" name="instructions" rows="4" required></textarea></div><div class="col-md-4"><label class="form-label">Maximum score</label><input type="number" class="form-control" name="max_score" value="10" min="0"></div></div><div id="taskOptions" class="mt-4"><h3 class="h6">Answer options</h3><p class="small text-muted">Select the best option and provide feedback for every choice.</p><?php for($i=0;$i<4;$i++):?><div class="row g-2 align-items-center mb-2"><div class="col-auto"><input class="form-check-input" type="radio" name="best_option" value="<?=$i?>" <?=$i===0?'required':''?>></div><div class="col-md"><input class="form-control" name="options[]" placeholder="Option <?=$i+1?>"></div><div class="col-md-2"><input type="number" class="form-control" name="option_scores[]" value="<?=$i===0?10:0?>" placeholder="Score"></div><div class="col-md"><input class="form-control" name="option_feedback[]" placeholder="Feedback"></div></div><?php endfor?></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save task</button></div></form></div></div>
<script>document.querySelectorAll('.add-simulation-task').forEach(button=>button.addEventListener('click',()=>{const form=document.getElementById('taskForm');form.reset();form.elements.simulation_id.value=button.dataset.id;document.getElementById('taskTarget').textContent=button.dataset.title;document.getElementById('taskOptions').classList.remove('d-none');bootstrap.Modal.getOrCreateInstance(document.getElementById('taskModal')).show()}));document.getElementById('taskType').addEventListener('change',function(){document.getElementById('taskOptions').classList.toggle('d-none',!['scenario_choice','case_study'].includes(this.value))});document.getElementById('taskForm').addEventListener('submit',async function(event){event.preventDefault();const button=this.querySelector('[type=submit]');button.disabled=true;try{const response=await fetch(APP.base+'admin/save_simulation_task.php',{method:'POST',body:new FormData(this),headers:{'X-CSRF-Token':APP.csrf}}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'Could not save task.');toast(data.message,'success');bootstrap.Modal.getInstance(document.getElementById('taskModal'))?.hide();setTimeout(()=>location.reload(),450)}catch(error){toast(error.message,'danger');button.disabled=false}});</script>
<?php require __DIR__.'/includes/footer.php';?>
