<?php
require_once dirname(__DIR__).'/includes/functions.php';require_role('counselor');$id=(int)($_GET['id']??0);
$stmt=$con->prepare("SELECT id,name,email,education_level,created_at FROM users WHERE id=? AND role='student' AND deleted_at IS NULL");$stmt->bind_param('i',$id);$stmt->execute();$student=$stmt->get_result()->fetch_assoc();if(!$student){http_response_code(404);exit('Student not found');}
$stmt=$con->prepare("SELECT s.title,p.status,p.total_score,p.max_possible_score,p.completed_at FROM user_simulation_progress p JOIN career_simulations s ON s.id=p.simulation_id WHERE p.user_id=? ORDER BY p.updated_at DESC");$stmt->bind_param('i',$id);$stmt->execute();$progress=$stmt->get_result();
$stmt=$con->prepare("SELECT c.title,q.title quiz,a.score,a.max_score,a.passed,a.completed_at FROM quiz_attempts a JOIN quizzes q ON q.id=a.quiz_id JOIN careers c ON c.id=q.career_id WHERE a.user_id=? ORDER BY a.completed_at DESC");$stmt->bind_param('i',$id);$stmt->execute();$quizzes=$stmt->get_result();
$stmt=$con->prepare("SELECT a.id attempt_id,t.title,t.max_score,a.response_text,a.ai_feedback,a.counselor_score,a.counselor_feedback,a.attempted_at FROM user_task_attempts a JOIN simulation_tasks t ON t.id=a.task_id WHERE a.user_id=? AND a.response_text IS NOT NULL AND a.response_text<>'' ORDER BY a.attempted_at DESC");$stmt->bind_param('i',$id);$stmt->execute();$responses=$stmt->get_result();
$pageTitle=$student['name'];require dirname(__DIR__).'/includes/header.php';?>
<div class="container py-5"><a href="<?=url('counselor/index.php')?>"><i class="bi bi-arrow-left"></i> Students</a><h1 class="mt-3"><?=e($student['name'])?></h1><p class="text-muted"><?=e($student['email'])?> · <?=e($student['education_level'])?></p><div class="row g-4">
<div class="col-lg-6"><div class="card p-4"><h2 class="h5">Simulation progress</h2><?php foreach($progress as $p):?><div class="border-bottom py-2"><strong><?=e($p['title'])?></strong><div class="small text-muted"><?=e($p['status'])?> · <?=$p['total_score']?> / <?=$p['max_possible_score']?></div></div><?php endforeach?></div></div>
<div class="col-lg-6"><div class="card p-4"><h2 class="h5">Quiz attempts</h2><?php foreach($quizzes as $q):?><div class="border-bottom py-2"><strong><?=e($q['quiz'])?></strong><div class="small text-muted"><?=$q['score']?> / <?=$q['max_score']?> · <?=$q['passed']?'Passed':'Not passed'?></div></div><?php endforeach?></div></div>
<div class="col-12"><div class="card p-4"><h2 class="h5">Written task responses</h2><?php if(!$responses->num_rows):?><p class="text-muted">No written responses yet.</p><?php endif?><?php foreach($responses as $r):?><div class="border-bottom py-3"><strong><?=e($r['title'])?></strong><p class="mb-1"><?=nl2br(e($r['response_text']))?></p><?php if($r['ai_feedback']):?><div class="alert alert-info py-2 small"><strong>AI coach:</strong> <?=e($r['ai_feedback'])?></div><?php endif?><div class="d-flex justify-content-between align-items-center mt-2"><small class="text-muted"><?=e($r['attempted_at'])?><?php if($r['counselor_score']!==null):?> · Graded <?=$r['counselor_score']?> / <?=$r['max_score']?><?php endif?></small><button class="btn btn-sm btn-outline-primary grade-attempt" data-row='<?=e(json_encode($r))?>'><?=$r['counselor_score']!==null?'Update review':'Grade response'?></button></div><?php if($r['counselor_feedback']):?><div class="alert alert-success py-2 small mt-2 mb-0"><strong>Counselor:</strong> <?=e($r['counselor_feedback'])?></div><?php endif?></div><?php endforeach?></div></div></div></div>
<div class="modal fade" id="gradeModal"><div class="modal-dialog"><form class="modal-content" action="<?=url('counselor/grade_attempt.php')?>" method="post" data-ajax><div class="modal-header"><h2 class="modal-title fs-5">Grade written response</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="attempt_id"><label class="form-label">Score <span id="gradeMaximum"></span></label><input type="number" class="form-control mb-3" name="score" min="0" required><label class="form-label">Counselor feedback</label><textarea class="form-control" name="feedback" rows="5" maxlength="2000" required></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save review</button></div></form></div></div>
<script>document.querySelectorAll('.grade-attempt').forEach(button=>button.addEventListener('click',()=>{const row=JSON.parse(button.dataset.row),form=document.querySelector('#gradeModal form');form.elements.attempt_id.value=row.attempt_id;form.elements.score.max=row.max_score;form.elements.score.value=row.counselor_score??0;form.elements.feedback.value=row.counselor_feedback??'';document.getElementById('gradeMaximum').textContent='(maximum '+row.max_score+')';bootstrap.Modal.getOrCreateInstance(document.getElementById('gradeModal')).show()}));</script>
<?php require dirname(__DIR__).'/includes/footer.php';?>
