<?php require_once __DIR__.'/functions.php'; $pageTitle=$pageTitle??'CareerSim'; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?=e($pageTitle)?> · CareerSim</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;600;700&family=Manrope:wght@400;600;700&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link href="<?=url('assets/css/custom.css')?>" rel="stylesheet">
<script>window.APP={base:'<?=url()?>',csrf:'<?=csrf_token()?>'};</script></head><body class="<?=e($bodyClass??'')?>">
<nav class="navbar navbar-expand-lg bg-white border-bottom sticky-top public-navbar"><div class="container-fluid px-3 px-lg-4"><a class="navbar-brand fw-bold" href="<?=url()?>">CareerSim</a>
<button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="nav"><ul class="navbar-nav ms-auto align-items-lg-center gap-lg-2">
<?php $currentPath=$_SERVER['PHP_SELF']??'';if(user()): ?><li><a class="nav-link <?=$currentPath&&str_contains($currentPath,'/careers/')?'active':''?>" href="<?=url('careers/browse.php')?>">Explore</a></li><li><a class="nav-link <?=$currentPath&&str_contains($currentPath,'/assessment/')?'active':''?>" href="<?=url('assessment/interest.php')?>">Assessment</a></li><li><a class="nav-link <?=$currentPath&&str_contains($currentPath,'/dashboard/progress')?'active':''?>" href="<?=url('dashboard/progress.php')?>">My progress</a></li>
<?php if(user()['role']==='student'):?><li><a class="nav-link <?=$currentPath&&str_contains($currentPath,'/jobs/')?'active':''?>" href="<?=url('jobs/browse.php')?>">Jobs</a></li><li><a class="nav-link <?=$currentPath&&str_contains($currentPath,'/dashboard/profile')?'active':''?>" href="<?=url('dashboard/profile.php')?>">Career profile</a></li><?php endif?>
<?php if(user()['role']==='counselor'):?><li><a class="nav-link <?=$currentPath&&str_contains($currentPath,'/counselor/')?'active':''?>" href="<?=url('counselor/index.php')?>">Counselor</a></li><li><a class="nav-link" href="<?=url('counselor/applications.php')?>">Applications</a></li><?php endif?><?php if(user()['role']==='admin'):?><li><a class="nav-link" href="<?=url('admin/index.php')?>">Admin</a></li><?php endif?><?php if(user()['role']==='content_manager'):?><li><a class="nav-link" href="<?=url('admin/careers.php')?>">Content manager</a></li><?php endif?>
<li class="dropdown"><button class="btn btn-light position-relative" data-bs-toggle="dropdown"><i class="bi bi-bell"></i><span id="unreadCount" class="badge rounded-pill bg-danger position-absolute top-0 start-100 translate-middle"></span></button><div id="notificationMenu" class="dropdown-menu dropdown-menu-end notification-menu p-2"></div></li>
<li><a class="btn btn-outline-primary" href="<?=url('auth/logout.php')?>">Sign out</a></li><?php else:?><li><a class="nav-link" href="<?=url('auth/login.php')?>">Sign in</a></li><li><a class="btn btn-primary" href="<?=url('auth/register.php')?>">Get started</a></li><?php endif?></ul></div></div></nav>
<main><?php foreach($_SESSION['flash']??[] as $f):?><div class="container mt-3"><div class="alert alert-<?=e($f['type'])?> alert-dismissible fade show"><?=e($f['message'])?><button class="btn-close" data-bs-dismiss="alert"></button></div></div><?php endforeach;unset($_SESSION['flash']);?>
